<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="hand">
  <!-- safety_distance: Minimum safety distance in [m] by which the collision volumes are expanded and which is enforced during robot motions -->
  <xacro:macro name="gripper_gazebo" params="link mu1:=10.0 mu2:=10.0">
    <gazebo reference="${link}">
      <mu1>${mu1}</mu1>
      <mu2>${mu2}</mu2>
      <maxVel>1</maxVel>
      <kp>1000000.0</kp>
      <kd>100.0</kd> 
      <fdir1>0 0 1</fdir1>
      <minDepth>0.0</minDepth>
      <maxContacts>100</maxContacts>
    </gazebo>
  </xacro:macro>

  <xacro:macro name="hand" params="connected_to:='' ns:='' rpy:='0 0 0' xyz:='0 0 0' safety_distance:=0">
    <xacro:unless value="${connected_to == ''}">
      <joint name="${ns}_hand_joint" type="fixed">
        <parent link="${connected_to}"/>
        <child link="${ns}_hand"/>
        <origin xyz="${xyz}" rpy="${rpy}"/>
      </joint>
    </xacro:unless>
    <link name="${ns}_hand">
      <inertial>
        <mass value="0.01"/>
        <origin rpy="0 0 0" xyz="0.0 0.0 0.0"/>
        <inertia ixx="0.000001" ixy="0.0" ixz="0.0" iyy="0.000001" iyz="0.0" izz="0.000001"/>
      </inertial>
      <visual>
        <geometry>
          <mesh filename="package://franka_description/meshes/visual/hand.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 0.0285" />
        <geometry>
          <box size="0.056 0.2 0.074" />
        </geometry>
      </collision>
      <!--
      <collision>
        <origin xyz="0 0 0.04" rpy="0 ${pi/2} ${pi/2}"/>
        <geometry>
          <cylinder radius="${0.04+safety_distance}" length="0.1" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 -0.05 0.04" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.04+safety_distance}"  />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0.05 0.04" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.04+safety_distance}"  />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 0.1" rpy="0 ${pi/2} ${pi/2}"/>
        <geometry>
          <cylinder radius="${0.02+safety_distance}" length="0.1" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 -0.05 0.1" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.02+safety_distance}"  />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0.05 0.1" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.02+safety_distance}"  />
        </geometry>
      </collision>
      -->
    </link>
    <link name="${ns}_leftfinger">
  <inertial>
     <mass value="0.014505"/>
     <origin rpy="0 0 0" xyz="3.299713e-07 0.013131 0.027017"/>
     <inertia ixx="4.338623e-06" ixy="0.0" ixz="0.0" iyy="4.027488e-06" iyz="0.0" izz="1.377502e-06"/>
  </inertial>
      <visual>
        <geometry>
          <mesh filename="package://franka_description/meshes/visual/finger.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0.0 0.0131 0.027" />
        <geometry>
          <box size="0.021 0.02643 0.0538" />
        </geometry>
      </collision>
    </link>
    <link name="${ns}_rightfinger">
  <inertial>
     <mass value="0.014505"/>
     <origin rpy="0 0 0" xyz="3.299713e-07 0.013131 0.027017"/>
     <inertia ixx="4.338623e-06" ixy="0.0" ixz="0.0" iyy="4.027488e-06" iyz="0.0" izz="1.377502e-06"/>
  </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 ${pi}"/>
        <geometry>
          <mesh filename="package://franka_description/meshes/visual/finger.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0.0 -0.0131 0.027" rpy="0 0 ${pi}"/>
        <geometry>
          <box size="0.021 0.02643 0.0538" />
        </geometry>
      </collision>
   </link>
    <joint name="${ns}_finger_joint1" type="prismatic">
      <parent link="${ns}_hand"/>
      <child link="${ns}_leftfinger"/>
      <origin xyz="0 0 0.0584" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit effort="20" lower="0.0" upper="0.04" velocity="0.2"/>
    </joint>
    <joint name="${ns}_finger_joint2" type="prismatic">
      <parent link="${ns}_hand"/>
      <child link="${ns}_rightfinger"/>
      <origin xyz="0 0 0.0584" rpy="0 0 0"/>
      <axis xyz="0 -1 0"/>
      <limit effort="20" lower="0.0" upper="0.04" velocity="0.2"/>
      <mimic joint="${ns}_finger_joint1" />
    </joint>
    <xacro:gripper_gazebo link="${ns}_hand"/>
    <xacro:gripper_gazebo link="${ns}_leftfinger"/>
    <xacro:gripper_gazebo link="${ns}_rightfinger"/>
  </xacro:macro>
</robot>
